services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: postgres_db
    env_file: ".env.yml"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: medication_db
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persists database data
    ports:
      - "5432:5432" # Maps the database service to localhost:5432
    restart: unless-stopped

  # Spring API
  spring-api:
    container_name: backend
    build:
      context: ./api # Path to the backend Dockerfile
      dockerfile: Dockerfile
    env_file: ".env.yml"
    ports:
      - "8080:8080"
    depends_on:
      - postgres # Ensure PostgreSQL starts before Spring Boot
    restart: unless-stopped

  # React Frontend
  react-ui:
    container_name: frontend
    build:
      context: ./client # Path to the frontend Dockerfile
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

volumes:
  postgres_data:
